# Generated by Django 6.1 on 2026-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
