# Generated by Django 6.1 on 2026-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_rating_business_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
