# Generated by Django 6.1 on 2026-09-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='businessimage',
            options={'verbose_name': 'Business Image', 'verbose_name_plural': 'Business Images'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
