# Generated by Django 6.1 on 2026-09-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_rename_reviews_review_alter_business_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
