# Generated by Django 6.1 on 2026-10-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_rename_review_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='price_range',
            field=models.CharField(default='$', max_length=3),
        ),
    ]
