# Generated by Django 6.1 on 2026-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
